title: "Prospero Station Job Board"
theme: minima
markdown: kramdown
baseurl: "/bl-job-board"
url: "https://sharperjbca.github.io"

collections:
  jobs:
    output: true
    permalink: /jobs/:name/
  locations:
    output: true
    permalink: /locations/:name/
  feed:
    output: true
    permalink: /feed/:name/

defaults:
  - scope:
      path: ""
      type: jobs
    values:
      layout: job
  - scope:
      path: ""
      type: locations
    values:
      layout: location
  - scope:
      path: ""
      type: feed
    values:
      layout: feed_post
sass:
  style: compressed