title: "Prospero Station Job Board"
theme: minima
markdown: kramdown
baseurl: "/bl_job_board"
url: "https://sharperjbca.github.io"

collections:
  jobs:
    output: true
    permalink: /jobs/:name/
  locations:
    output: true
    permalink: /locations/:name/
  feed:
    output: true
    permalink: /feed/:name/

defaults:
  - scope:
      path: ""
      type: jobs
    values:
      layout: job
  - scope:
      path: ""
      type: locations
    values:
      layout: location
  - scope:
      path: ""
      type: feed
    values:
      layout: feed_post
sass:
  style: compressed


supabase:
  url: "https://yrzwvueictbyolgfhvfv.supabase.co"
  anon_key: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlyend2dWVpY3RieW9sZ2ZodmZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzE2NjkzMDEsImV4cCI6MjA4NzI0NTMwMX0.H10R5Befp1ktsul31bZgkA4kZ02_IPkEW51wUAJY9no"
